{
 "title": "LiteLLM",
 "description": "Visualization for monitoring LiteLLM request latency, usage, tokens, and routes using Azure Monitor (Application Insights) in a single Grafana dashboard.",
 "tags": [
  "Azure Monitor",
  "LiteLLM",
  "Application Insihgts"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "subscriptionId",
    "label": "Subscription",
    "query": {}
   },
   {
    "name": "applicationInsightsResourceId",
    "label": "Application Insights",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Trend",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 22, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": true,
      "query": "dependencies\r\n| where name == \"litellm_request\"\r\n| summarize \r\n    avg = avg(duration),\r\n    p75 = percentile(duration, 75),\r\n    p90 = percentile(duration, 90),\r\n    p95 = percentile(duration, 95),\r\n    p99 = percentile(duration, 99)\r\n    by bin(timestamp, 1d)\r\n| order by timestamp asc\r\n",
      "resources": [ "$applicationInsightsResourceId" ],
      "resultFormat": "time_series",
      "timeColumn": "timestamp"
     }
    }
   ]
  },
  {
   "title": "Latency by model",
   "type": "table",
   "gridPos": { "h": 10, "w": 22, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": true,
      "query": "dependencies\r\n| where name == \"litellm_request\"\r\n| extend model = tostring(customDimensions[\"gen_ai.request.model\"])\r\n| summarize\r\n    avg  = avg(duration),\r\n    p75  = percentile(duration, 75),\r\n    p90  = percentile(duration, 90),\r\n    p95  = percentile(duration, 95),\r\n    p99  = percentile(duration, 99)\r\n    by model\r\n| order by avg desc",
      "resources": [ "$applicationInsightsResourceId" ],
      "resultFormat": "time_series",
      "timeColumn": "timestamp"
     }
    }
   ]
  },
  { "title": "Usage by model", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "LLM Requests",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 22 },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "dependencies\r\n| where name == \"litellm_request\"\r\n| extend gen_ai_request_model = tostring(customDimensions.[\"gen_ai.request.model\"])\r\n| make-series requestCount=count() default=0 \r\n    on timestamp \r\n    in range($__timeFrom(), $__timeTo(), 1d) \r\n    by gen_ai_request_model\r\n| mv-expand timestamp to typeof(datetime), requestCount to typeof(long)\r\n| project timestamp, gen_ai_request_model, requestCount\r\n| order by timestamp asc\r\n",
      "resources": [ "$applicationInsightsResourceId" ],
      "resultFormat": "time_series",
      "timeColumn": "timestamp"
     }
    }
   ]
  },
  {
   "title": "LLM Tokens",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 11, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "dependencies\r\n| where name == \"litellm_request\"\r\n| extend gen_ai_request_model = tostring(customDimensions.[\"gen_ai.request.model\"])\r\n| extend llm_usage_total_tokens = toint(customDimensions.[\"llm.usage.total_tokens\"])\r\n| make-series tokenCount=sum(llm_usage_total_tokens) default=0 \r\n    on timestamp \r\n    in range($__timeFrom(), $__timeTo(), 1d) \r\n    by gen_ai_request_model\r\n| mv-expand timestamp to typeof(datetime), tokenCount to typeof(long)\r\n| project timestamp, gen_ai_request_model, tokenCount\r\n| order by timestamp asc\r\n",
      "resources": [ "$applicationInsightsResourceId" ],
      "resultFormat": "time_series",
      "timeColumn": "timestamp"
     }
    }
   ]
  },
  { "title": "Usage by request route", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "LLM Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 33 },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "dependencies\r\n| where name == \"litellm_request\"\r\n| extend request_route = tostring(customDimensions.[\"metadata.user_api_key_request_route\"])\r\n| extend gen_ai_request_model = tostring(customDimensions.[\"gen_ai.request.model\"])\r\n| make-series requestCount=count() default=0 \r\n    on timestamp \r\n    in range($__timeFrom(), $__timeTo(), 1d) \r\n    by request_route\r\n| mv-expand timestamp to typeof(datetime), requestCount to typeof(long)\r\n| project timestamp, request_route, requestCount\r\n| order by timestamp asc\r\n",
      "resources": [ "$applicationInsightsResourceId" ],
      "resultFormat": "time_series",
      "timeColumn": "timestamp"
     }
    }
   ]
  },
  {
   "title": "LLM Tokens",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 11, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "dependencies\r\n| where name == \"litellm_request\"\r\n| extend request_route = tostring(customDimensions.[\"metadata.user_api_key_request_route\"])\r\n| extend gen_ai_request_model = tostring(customDimensions.[\"gen_ai.request.model\"])\r\n| extend llm_usage_total_tokens = toint(customDimensions.[\"llm.usage.total_tokens\"])\r\n| make-series tokenCount=sum(llm_usage_total_tokens) default=0 \r\n    on timestamp \r\n    in range($__timeFrom(), $__timeTo(), 1d) \r\n    by request_route\r\n| mv-expand timestamp to typeof(datetime), tokenCount to typeof(long)\r\n| project timestamp, request_route, tokenCount\r\n| order by timestamp asc\r\n",
      "resources": [ "$applicationInsightsResourceId" ],
      "resultFormat": "time_series",
      "timeColumn": "timestamp"
     }
    }
   ]
  },
  { "title": "Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Recent LLM calls",
   "type": "logs",
   "gridPos": { "h": 22, "w": 22, "x": 0, "y": 43 },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": true,
      "query": "dependencies\r\n| where name == \"litellm_request\"\r\n| extend request_route = tostring(customDimensions.[\"metadata.user_api_key_request_route\"])\r\n| extend gen_ai_request_model = tostring(customDimensions.[\"gen_ai.request.model\"])\r\n| extend gen_ai_system = tostring(customDimensions.[\"gen_ai.system\"])\r\n| extend gen_ai_usage_completion_tokens = tostring(customDimensions.[\"gen_ai.usage.completion_tokens\"])\r\n| extend gen_ai_usage_prompt_tokens = tostring(customDimensions.[\"gen_ai.usage.prompt_tokens\"])\r\n| extend llm_usage_total_tokens = tostring(customDimensions.[\"llm.usage.total_tokens\"])\r\n| order by timestamp desc\r\n| project-reorder gen_ai_request_model, request_route, gen_ai_usage_prompt_tokens, gen_ai_usage_completion_tokens, llm_usage_total_tokens\r\n| limit 100",
      "resources": [ "$applicationInsightsResourceId" ],
      "resultFormat": "logs",
      "timeColumn": "timestamp"
     }
    }
   ]
  }
 ]
}